right_format = """
$status\
$cmd_duration\
$time\
"""

format = """
$username\
[${custom.separator}](fg:prev_bg bg:dir_bg)\
$directory\
[${custom.separator}](fg:prev_bg bg:git_bg)\
$git_branch\
$git_status\
$kubernetes\
[\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$python\
$rust\
$scala\
](fg:code_fg bg:code_bg)\
[${custom.separator}](fg:prev_bg)\
${custom.dualline}\
$character\
"""

# add new line for spacing between commands
add_newline = true

palette = "devon"

[palettes.devon]
user_bg = "#1b1d1e"
user_fg = "253"
dir_bg = "#4e82aa"
dir_fg = "#000000"
git_bg = "#82b414"
git_fg = "#253"
k8s_bg = "yellow"
k8s_fg = "#000000"
code_bg = "#4e82aa"
code_fg = "#111111"
extra_fg = "#222222"

[custom.separator]
when = true
symbol = ""
format = '$symbol'

[custom.dualline]
when = true
format = " \n "


# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:user_bg fg:user_fg"
style_root = "bg:user_bg fg:user_fg bold"
format = '[ $user ]($style)'
disabled = false


[directory]
format = "[ $path ]($style)"
style = 'bg:dir_bg fg:dir_fg'
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "


[git_branch]
style = "bg:prev_bg fg:prev_fg"
symbol = ""
format = '[ $symbol $branch]($style)'

[git_status]
style = "bg:prev_bg fg:prev_fg"
format = '[ $all_status$ahead_behind ]($style)'



[kubernetes]
disabled = false
style = "bg:k8s_bg fg:k8s_fg"
format = '$symbol[ $context ]($style)[](fg:prev_bg bg:code_bg)'
symbol = "[ 󱃾](fg:prev_bg bg:k8s_bg)"

[[kubernetes.contexts]]
# "bold red" style + default symbol when Kubernetes current context name equals "production" *and* the current user
# equals "admin_user"
context_pattern = "defdault"
style = "bold bg:red"
symbol = "[ 󱃾](fg:prev_bg bg:red)"

[c]
symbol = " "
style = "fg:code_fg bg:code_bg"
format = '[ $symbol ($version) ]($style)'

[elixir]
symbol = " "
style = "fg:code_fg bg:code_bg"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "fg:code_fg bg:code_bg"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = " "
style = "fg:code_fg bg:code_bg"
format = '[ $symbol ($version) ]($style)'

[gradle]
format = '[ $symbol ($version) ]($style)'
style = "fg:code_fg bg:code_bg"

[haskell]
symbol = " "
style = "fg:code_fg bg:code_bg"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "fg:code_fg bg:code_bg"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "fg:code_fg bg:code_bg"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "fg:code_fg bg:code_bg"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "fg:code_fg bg:code_bg"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style = "fg:code_fg bg:code_bg"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "fg:code_fg bg:code_bg"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "fg:code_fg bg:code_bg"
format = '[ $symbol ($version) ]($style)'


[cmd_duration]
disabled = false
min_time = 1000
style = "fg:extra_fg"
format = '[ 󱎫 $duration ]($style)'

[status]
disabled = false
style = ''
format = '[ $symbol ]($style)'
pipestatus_format = '[ $pipestatus ]($style)'
map_symbol = true
pipestatus = true
recognize_signal_code = true
symbol = '[✗](bold red)'
success_symbol = '[✓](green)'
not_executable_symbol = '[󰩋](bold fg:red)'
not_found_symbol = '[](bold fg:red)'
sigint_symbol = '[⚡](fg:yellow)'
signal_symbol = '[⚡](bold fg:red)'


[character]
success_symbol = '[❯](bold white) '
error_symbol = '[❯](bold white) '

[time]
disabled = false
format = '[$time]($style) '
style = 'fg:extra_fg'
use_12hr = true
time_format = '%b %-e %-l:%-M:%-S %P'
utc_time_offset = 'local'